Repository libigl/libigl, pull requests merged in 2018-10, with the labels that each got.

#917 Fix redux
  include/igl/redux.h
  tutorial/505_MIQ/main.cpp
Labels: hackathon-easy

#612 Fix for a segfault when attempting to load a non-existant obj mesh th…
  include/igl/read_triangle_mesh.cpp
Labels: hackathon-easy

#856 Make avg_edge_length() count interior edges only once.
  include/igl/adjacency_matrix.cpp
  include/igl/avg_edge_length.cpp
  include/igl/avg_edge_length.h
  include/igl/edges.cpp
  include/igl/median.cpp
Labels: hackathon-easy

#857 Minor fixes to the viewer.
  include/igl/opengl/glfw/Viewer.cpp
  include/igl/opengl/glfw/imgui/ImGuiMenu.cpp
Labels: bug, hackathon-easy, viewer

#530 add while loop for comb_cross_field.cpp, making comb support separated manifold
  include/igl/comb_cross_field.cpp
  include/igl/opengl/glfw/Viewer.cpp
Labels: hackathon-maybe

#809 Code to cut meshes into topological disks
  include/igl/cut_to_disk.cpp
  include/igl/cut_to_disk.h
Labels: hackathon-maybe

#752 Adding 2D version of SCAF for Bijective Maps and a tutorial
  include/igl/MappingEnergyType.h
  include/igl/mapping_energy_with_jacobians.cpp
  include/igl/mapping_energy_with_jacobians.h
  include/igl/scaf.cpp
  include/igl/scaf.h
  include/igl/slice.cpp
  include/igl/slim.cpp
  include/igl/slim.h
  include/igl/sparse_cached.h
  include/igl/topological_hole_fill.cpp
  include/igl/topological_hole_fill.h
  tutorial/709_SLIM/CMakeLists.txt
  tutorial/709_SLIM/main.cpp
  tutorial/710_SCAF/CMakeLists.txt
  tutorial/710_SCAF/main.cpp
  tutorial/CMakeLists.txt
  tutorial/images/710_SCAF.png
  tutorial/shared/camel_b.obj
Labels: hackathon-easy

#819 fix: principal_curvature returns vector of bad vertex indices
  include/igl/principal_curvature.cpp
  include/igl/principal_curvature.h
Labels: hackathon-maybe

#839 Make libigl installable using CMake
  CMakeLists.txt
  optional/CMakeLists.txt
  shared/cmake/libigl-config.cmake.in
  shared/cmake/libigl.cmake
Labels: cmake, hackathon-maybe

#716 Marching Tetrahedra
  include/igl/marching_tets.cpp
  include/igl/marching_tets.h
  include/igl/slice_tets.cpp
  include/igl/slice_tets.h
  include/igl/writeDMAT.cpp
  python/py_doc.cpp
  python/py_doc.h
  python/py_igl.cpp
  python/py_igl/py_marching_tets.cpp
  python/python_shared.cpp
  python/tutorial/702_WindingNumber.py
  python/tutorial/704_SignedDistance.py
  tutorial/702_WindingNumber/main.cpp
  tutorial/704_SignedDistance/main.cpp
  tutorial/714_MarchingTets/CMakeLists.txt
  tutorial/714_MarchingTets/main.cpp
  tutorial/CMakeLists.txt
Labels: hackathon-easy

#956 delaunay unit tests, expose is_delaunay, templates, PlainObject -> Matrix
  include/igl/copyleft/cgal/delaunay_triangulation.cpp
  include/igl/copyleft/cgal/delaunay_triangulation.h
  include/igl/copyleft/cgal/hausdorff.cpp
  include/igl/copyleft/cgal/incircle.cpp
  include/igl/copyleft/cgal/orient2D.cpp
  include/igl/delaunay_triangulation.cpp
  include/igl/delaunay_triangulation.h
  include/igl/flip_edge.cpp
  include/igl/is_delaunay.cpp
  include/igl/is_delaunay.h
  include/igl/lexicographic_triangulation.cpp
  include/igl/lexicographic_triangulation.h
  include/igl/matlab_format.cpp
  include/igl/oriented_facets.h
  include/igl/principal_curvature.cpp
  include/igl/scaf.cpp
  include/igl/topological_hole_fill.cpp
  include/igl/unique_edge_map.cpp
  include/igl/unique_edge_map.h
  tests/include/igl/copyleft/cgal/delaunay_triangulation.cpp
  tests/include/igl/is_delaunay.cpp
  tests/include/igl/unique_simplices.cpp
Labels: unit-tests

#960 enabled testing on windows
  .appveyor.yml
  CMakeLists.txt
  cmake/LibiglWindows.cmake
  include/igl/bbw.cpp
Labels: unit-tests
