Repository libigl/libigl, pull requests merged in 2021-03, with the labels that each got.

#1744 Silence MSVC warning with std::getenv.
  include/igl/default_num_threads.cpp
Labels: compilation

#1746 Split min_quad_with_fixed implementation into separate cpp.
  .github/workflows/continuous.yml
  .github/workflows/nightly.yml
  include/igl/min_quad_with_fixed.1.cpp
  include/igl/min_quad_with_fixed.2.cpp
  include/igl/min_quad_with_fixed.h
  include/igl/min_quad_with_fixed.impl.h
  include/igl/min_quad_with_fixed_precompute.cpp
  include/igl/min_quad_with_fixed_solve.cpp
Labels: compilation

#1747 Fix Cuda compilation issue on Windows.
  cmake/libigl.cmake
Labels: compilation

#1748 Use boost via conda on Windows.
  .github/workflows/continuous.yml
  .github/workflows/nightly.yml
Labels: compilation

#1752 Replace Eigen::PlainObjectBase with Eigen::MatrixBase for input of ambient_occlusion
  include/igl/embree/ambient_occlusion.cpp
  include/igl/embree/ambient_occlusion.h
Labels: enhancement

#1761 Fix dirty flag for ViewerData::set_labels
  include/igl/opengl/ViewerData.cpp
Labels: bug

#1762 Fix boost conda failure in nightly build.
  .github/workflows/nightly.yml
Labels: compilation

#1765 Added double_sided flag to embree renderer
  include/igl/embree/EmbreeRenderer.cpp
  include/igl/embree/EmbreeRenderer.h
Labels: enhancement

#1768 Use igl::default_num_threads in cgal module.
  .github/workflows/continuous.yml
  .github/workflows/nightly.yml
  include/igl/copyleft/cgal/SelfIntersectMesh.h
Labels: enhancement
