Repository libigl/libigl, pull requests merged in 2021-02, with the labels that each got.

#1721 Update job name in github actions.
  .github/workflows/continuous.yml
  .github/workflows/nightly.yml
Labels: compilation

#1440 solve fragmentation issue with remesh_along_isoline (cleaned up)
  include/igl/remesh_along_isoline.cpp
  tests/include/igl/remesh_along_isoline.cpp
Labels: waiting for review

#1684 Control number of threads with IGL_PARALLEL_FOR_NUM_THREADS
  include/igl/default_num_threads.cpp
  include/igl/default_num_threads.h
  include/igl/parallel_for.h
Labels: enhancement

#1723 Update ImGui to 1.81+
  cmake/LibiglDownloadExternal.cmake
Labels: bug, viewer

#1733 Fix usage of find_package(OpenGL) on Linux
  cmake/libigl.cmake
Labels: compilation
