Repository libigl/libigl, pull requests merged in 2021-04, with the labels that each got.

#1767 Fix the order of principal curvature
  include/igl/principal_curvature.cpp
  tests/include/igl/principal_curvature.cpp
  tutorial/203_CurvatureDirections/main.cpp
Labels: bug

#1745 10-100x speedup on per corner normals + caching adjacency
  include/igl/cumsum.cpp
  include/igl/per_corner_normals.cpp
  include/igl/per_corner_normals.h
  include/igl/smooth_corner_adjacency.cpp
  include/igl/smooth_corner_adjacency.h
  include/igl/unzip_corners.h
  include/igl/vertex_triangle_adjacency.cpp
Labels: performance

#1786 Update github actions.
  .github/workflows/continuous.yml
  .github/workflows/nightly.yml
Labels: compilation

#1796 Fix 1795
  include/igl/copyleft/cgal/polyhedron_to_mesh.cpp
Labels: compilation
