Repository libigl/libigl, pull requests merged in 2022-03, with the labels that each got.

#1985 Compile GMP and MPFR from source
  .github/workflows/continuous.yml
  CMakeLists.txt
  cmake/recipes/external/gmp.cmake
  cmake/recipes/external/gmp_mpfr.cmake
  cmake/recipes/external/mpfr.cmake
Labels: compilation, cgal

#2010 Improved draw_buffer
  include/igl/opengl/ViewerCore.cpp
  include/igl/opengl/ViewerCore.h
  include/igl/opengl/glfw/Viewer.cpp
  include/igl/opengl/glfw/Viewer.h
Labels: viewer

#1819 Rework sparse repmat
  include/igl/repmat.cpp
  include/igl/repmat.h
  tests/include/igl/repmat.cpp
Labels: enhancement
