Repository libigl/libigl, pull requests merged in 2023-08, with the labels that each got.

#1693 Separated png module from opengl, added unit test for png
  CMakeLists.txt
  LibiglOptions.cmake.sample
  cmake/igl/modules/png.cmake
  cmake/igl/modules/stb.cmake
  cmake/libigl.cmake
  include/igl/opengl/stb/render_to_file.cpp
  include/igl/opengl/stb/render_to_file.h
  include/igl/opengl/stb/render_to_file_async.cpp
  include/igl/opengl/stb/render_to_file_async.h
  include/igl/png/readPNG.h
  include/igl/png/render_to_png.h
  include/igl/png/render_to_png_async.h
  include/igl/png/texture_from_file.cpp
  include/igl/png/texture_from_file.h
  include/igl/png/texture_from_png.cpp
  include/igl/png/texture_from_png.h
  include/igl/png/writePNG.h
  include/igl/stb/read_image.cpp
  include/igl/stb/read_image.h
  include/igl/stb/write_image.cpp
  include/igl/stb/write_image.h
  tests/include/igl/stb/read_write.cpp
  tests/include/igl/stb/test_bmp.h
  tests/include/igl/stb/test_jpg.h
  tests/include/igl/stb/test_pgm.h
  tests/include/igl/stb/test_png.h
  tests/include/igl/stb/test_reference.h
  tests/include/igl/stb/test_tga.h
  tutorial/111_MatCap/main.cpp
  tutorial/113_Shadows/main.cpp
  tutorial/607_ScreenCapture/main.cpp
  tutorial/608_RayTrace/main.cpp
  tutorial/CMakeLists.txt
Labels: discussion needed

#1413 Speed up of SelfIntersectMesh:
  include/igl/copyleft/cgal/SelfIntersectMesh.h
Labels: enhancement, cgal, waiting for review

#1565 Ear clipping function fix
  include/igl/predicates/ear_clipping.cpp
  include/igl/predicates/ear_clipping.h
  include/igl/predicates/polygons_to_triangles.cpp
  tests/include/igl/predicates/ear_clipping.cpp
Labels: waiting for review
